### ISSUE TITLE
Excited!

### ISSUE THREAD

**Issue by txbondboy** [MediaGithub/LeagueSharpDev#1]
Was wanting an ETA maybe! also i couldn't get rid of drawings.

**Comment by KyonLeague** [comment]
Was wanting proper English maybe ? :^)

**Comment by txbondboy** [comment]
Really? All I wanted was some info on something I'm excited on. You didn't need to be a dick about it.

**Comment by KyonLeague** [comment]
I don't want to be rude or something like that, but please keep in your mind, that some of us got some real life jobs and because of that there won't be any eta. :)
